param(
    [Parameter(Mandatory=$true)]
    [string]$ApiKey
)

# Set error action preference to stop on any error
$ErrorActionPreference = "Stop"

# --- INPUT VALIDATION ---
if ([string]::IsNullOrWhiteSpace($ApiKey) -or $ApiKey -notmatch '^csai-[a-zA-Z0-9-]+$') {
    Write-Host "❌ Missing or invalid API key." -ForegroundColor Red
    Write-Host "Usage: .\script.ps1 -ApiKey <your-api-key>"
    Write-Host "Example: .\script.ps1 -ApiKey csai-ca-abc123def..."
    exit 1
}

# --- CONSTANTS ---
$ConfigDir = Join-Path $env:USERPROFILE ".claude"
$ConfigPath = Join-Path $env:USERPROFILE ".claude\settings.json"
$BackupPrefix = Join-Path $env:USERPROFILE ".claude\settings.json.bak"
$AutoStart = "// === AUTO-GENERATED BY COSTA START ==="
$AutoEnd = "// === AUTO-GENERATED BY COSTA END ==="
$RemoteUrl = "https://raw.githubusercontent.com/costa-security/install/refs/heads/main/claude/settings.json"

# --- CREATE CONFIG DIRECTORY ---
if (-not (Test-Path $ConfigDir)) {
    Write-Host "📁 Creating Claude Code config directory..."
    New-Item -ItemType Directory -Path $ConfigDir | Out-Null
}

try {
    # --- FETCH CONFIG BLOCK ---
    Write-Host "🌐 Downloading Claude Code config block..."
    $RemoteContent = Invoke-WebRequest -Uri $RemoteUrl -UseBasicParsing | Select-Object -ExpandProperty Content

    # Extract the auto-generated block
    $Lines = $RemoteContent -split "`r?`n"
    $InBlock = $false
    $NewBlockLines = @()

    foreach ($Line in $Lines) {
        if ($Line.Trim() -eq $AutoStart) {
            $InBlock = $true
        }
        if ($InBlock) {
            $NewBlockLines += $Line
        }
        if ($Line.Trim() -eq $AutoEnd) {
            $InBlock = $false
        }
    }

    if ($NewBlockLines.Count -eq 0) {
        Write-Host "❌ Failed to extract AUTO-GENERATED block from remote config." -ForegroundColor Red
        exit 1
    }

    # Inject API key
    $NewBlock = ($NewBlockLines -join "`n") -replace "REPLACE_WITH_YOUR_API_KEY", $ApiKey

    # --- REPLACE OR INSTALL ---
    if (Test-Path $ConfigPath) {
        $ConfigContent = Get-Content $ConfigPath -Raw

        if ($ConfigContent -match [regex]::Escape($AutoStart)) {
            # Replace the auto-generated block using regex with SingleLine option
            $Pattern = "(?s)" + [regex]::Escape($AutoStart) + ".*?" + [regex]::Escape($AutoEnd)
            $UpdatedContent = $ConfigContent -replace $Pattern, $NewBlock

            Set-Content -Path $ConfigPath -Value $UpdatedContent -Encoding UTF8
            Write-Host "✅ Replaced existing Costa config block in settings.json" -ForegroundColor Green
        }
        else {
            # Backup and write full new file
            $i = 1
            $Backup = $BackupPrefix
            while (Test-Path $Backup) {
                $i++
                $Backup = "${BackupPrefix}${i}"
            }

            Move-Item $ConfigPath $Backup
            Write-Host "🗃️ Backed up original config to $(Split-Path $Backup -Leaf)" -ForegroundColor Cyan

            Set-Content -Path $ConfigPath -Value $NewBlock -Encoding UTF8
            Write-Host "✅ Installed Costa config as new file" -ForegroundColor Green
        }
    }
    else {
        Set-Content -Path $ConfigPath -Value $NewBlock -Encoding UTF8
        Write-Host "✅ Created new settings.json with Costa config" -ForegroundColor Green
    }

    Write-Host "🎉 Claude Code has been configured with your Costa API key!" -ForegroundColor Green
    Write-Host "   The configuration has been saved to $ConfigPath" -ForegroundColor White
    Write-Host "   You can now use Claude Code with your Costa account." -ForegroundColor White
}
catch {
    Write-Host "❌ An error occurred: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}