#!/bin/bash

set -euo pipefail

# --- INPUT ---
API_KEY="${1:-}"

# Validate API key format (basic check, optional)
if [[ -z "$API_KEY" || ! "$API_KEY" =~ ^csai-[a-zA-Z0-9-]+$ ]]; then
  echo "❌ Missing or invalid API key."
  echo "Usage: curl ... | bash -s -- <your-api-key>"
  echo "Example: curl ... | bash -s -- csai-ca-abc123def..."
  exit 1
fi

# --- CONSTANTS ---
CONFIG_DIR="$HOME/.claude"
CONFIG_PATH="$HOME/.claude/settings.json"
BACKUP_PREFIX="$HOME/.claude/settings.json.bak"
TEMP_FILE="$(mktemp)"
NEW_BLOCK_FILE="$(mktemp)"
AUTO_START="// === AUTO-GENERATED BY COSTA START ==="
AUTO_END="// === AUTO-GENERATED BY COSTA END ==="
REMOTE_URL="https://raw.githubusercontent.com/costa-security/install/refs/heads/main/claude/settings.json"

# --- CHECK PLATFORM ---
PLATFORM="$(uname)"
if [[ "$PLATFORM" != "Darwin" && "$PLATFORM" != "Linux" ]]; then
  echo "🚫 This script is only supported on macOS and Linux. Exiting."
  exit 1
fi

# --- CREATE CONFIG DIRECTORY ---
if [[ ! -d "$CONFIG_DIR" ]]; then
  echo "📁 Creating Claude Code config directory..."
  mkdir -p "$CONFIG_DIR"
fi

# --- FETCH CONFIG BLOCK ---
echo "🌐 Downloading Claude Code config block..."
REMOTE_CONTENT=$(curl -fsSL "$REMOTE_URL")

# Extract the auto-generated block
NEW_BLOCK=$(echo "$REMOTE_CONTENT" | awk "/$AUTO_START/{flag=1} flag; /$AUTO_END/{flag=0}")

if [[ -z "$NEW_BLOCK" ]]; then
  echo "❌ Failed to extract AUTO-GENERATED block from remote config."
  exit 1
fi

# Inject API key
NEW_BLOCK="${NEW_BLOCK//REPLACE_WITH_YOUR_API_KEY/$API_KEY}"

# Write to temp file for safe processing
echo "$NEW_BLOCK" > "$NEW_BLOCK_FILE"

# --- REPLACE OR INSTALL ---
if [[ -f "$CONFIG_PATH" ]]; then
  if grep -q "$AUTO_START" "$CONFIG_PATH"; then
    # Replace the auto-generated block using awk with file input
    awk -v start="$AUTO_START" -v end="$AUTO_END" -v repl_file="$NEW_BLOCK_FILE" '
      BEGIN {
        in_block = 0
        while ((getline line < repl_file) > 0) {
          repl[++n] = line
        }
        close(repl_file)
      }
      $0 ~ start {
        print repl[1]
        for (i = 2; i <= n; i++) print repl[i]
        in_block = 1
        next
      }
      $0 ~ end {
        in_block = 0
        next
      }
      !in_block {
        print
      }
    ' "$CONFIG_PATH" > "$TEMP_FILE"

    mv "$TEMP_FILE" "$CONFIG_PATH"
    echo "✅ Replaced existing Costa config block in settings.json"
  else
    # Backup and write full new file
    i=1
    backup="$BACKUP_PREFIX"
    while [[ -f "$backup" ]]; do
      i=$((i+1))
      backup="${BACKUP_PREFIX}${i}"
    done
    mv "$CONFIG_PATH" "$backup"
    echo "🗃️ Backed up original config to $(basename "$backup")"

    cp "$NEW_BLOCK_FILE" "$CONFIG_PATH"
    echo "✅ Installed Costa config as new file"
  fi
else
  cp "$NEW_BLOCK_FILE" "$CONFIG_PATH"
  echo "✅ Created new settings.json with Costa config"
fi

# --- CLEANUP ---
rm -f "$NEW_BLOCK_FILE"

echo "🎉 Claude Code has been configured with your Costa API key!"
echo "   The configuration has been saved to $CONFIG_PATH"
echo "   You can now use Claude Code with your Costa account."